2025-01-25 08:24:02,522 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,522 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421160>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,524 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,524 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420e30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,526 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044207d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,526 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420230>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,528 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10666a4e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,528 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420200>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,529 ERROR  Error while scraping channel info for @YesTheory: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,529 ERROR  Error while scraping channel info for @BeastReacts: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,531 INFO  Scraping complete for @YesTheory
2025-01-25 08:24:02,531 INFO  Scraping complete for @BeastReacts
2025-01-25 08:24:02,533 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044053d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,533 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407cb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,535 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405c10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,535 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407530>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,537 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406960>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,537 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104406840>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,539 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044218e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,539 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044201a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,540 ERROR  Error while scraping channel info for @MrBeastGaming: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,540 ERROR  Error while scraping channel info for @Dream: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,542 INFO  Scraping complete for @MrBeastGaming
2025-01-25 08:24:02,542 INFO  Scraping complete for @Dream
2025-01-25 08:24:02,544 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420e00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,544 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420470>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,546 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420f50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,546 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,548 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044073b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,548 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407650>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,550 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407b00>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,550 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407830>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,551 ERROR  Error while scraping channel info for @Sapnap: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,551 ERROR  Error while scraping channel info for @GeorgeNotFound: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,552 INFO  Scraping complete for @Sapnap
2025-01-25 08:24:02,552 INFO  Scraping complete for @GeorgeNotFound
2025-01-25 08:24:02,554 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668dc70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,554 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e8a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,556 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,556 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d070>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,558 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044066f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,558 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407920>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,560 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044078f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,560 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044072f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,561 ERROR  Error while scraping channel info for @Technoblade: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,561 ERROR  Error while scraping channel info for @TommyInnit: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,562 INFO  Scraping complete for @Technoblade
2025-01-25 08:24:02,563 INFO  Scraping complete for @TommyInnit
2025-01-25 08:24:02,564 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420f50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,564 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044202f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,566 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044216a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,566 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044215b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,568 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ed80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,568 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cf80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,570 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d160>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,570 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ffe0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,571 ERROR  Error while scraping channel info for @WilburSoot: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,571 ERROR  Error while scraping channel info for @Tubbo: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,572 INFO  Scraping complete for @WilburSoot
2025-01-25 08:24:02,572 INFO  Scraping complete for @Tubbo
2025-01-25 08:24:02,574 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f860>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,574 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d9a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,576 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668f020>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,576 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668ecc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,602 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668d0a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,602 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668edb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,604 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421160>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,604 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e510>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,605 ERROR  Error while scraping channel info for @Stampylonghead: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,605 ERROR  Error while scraping channel info for @Ranboo: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,607 INFO  Scraping complete for @Stampylonghead
2025-01-25 08:24:02,607 INFO  Scraping complete for @Ranboo
2025-01-25 08:24:02,632 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104420110>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,633 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405250>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,635 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407950>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,635 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407a40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,637 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f770>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,637 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407140>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,640 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658d3a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,640 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520050>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,641 ERROR  Error while scraping channel info for @PopularMMOs: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,641 ERROR  Error while scraping channel info for @DanTDM: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,642 INFO  Scraping complete for @PopularMMOs
2025-01-25 08:24:02,642 INFO  Scraping complete for @DanTDM
2025-01-25 08:24:02,645 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10666a4e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,645 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520530>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,647 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658ff20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,647 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10658f800>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,650 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104407050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,650 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104405730>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,652 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044072c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,652 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104421730>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,653 ERROR  Error while scraping channel info for @Jacksepticeye: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,653 ERROR  Error while scraping channel info for @Ninja: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,654 INFO  Scraping complete for @Jacksepticeye
2025-01-25 08:24:02,655 INFO  Scraping complete for @Ninja
2025-01-25 08:24:02,657 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668f3b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,657 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668dc40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,659 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668cf80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,659 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e030>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,661 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e634d31ac5044156891874464f1c9890/url
2025-01-25 08:24:02,661 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10668e9c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2bbb52b65325103010e69e5d1ee922ec/url
2025-01-25 08:24:02,664 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51664): Max retries exceeded with url: /session/2bbb52b65325103010e69e5d1ee922ec/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1065209b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,664 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=51634): Max retries exceeded with url: /session/e634d31ac5044156891874464f1c9890/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106520830>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 08:24:02,665 ERROR  Error while scraping channel info for @Shroud: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,665 ERROR  Error while scraping channel info for @Pokimane: 'dict' object has no attribute 'model_dump_json'
2025-01-25 08:24:02,667 INFO  Scraping complete for @Shroud
2025-01-25 08:24:02,667 INFO  Scraping complete for @Pokimane
