2025-01-25 16:20:24,384 INFO  Fetching channel name and verification status.
2025-01-25 16:20:24,423 INFO  Clicking 'More' button to fetch about info.
2025-01-25 16:20:25,967 INFO  Fetching channel name and verification status.
2025-01-25 16:20:26,093 INFO  Clicking 'More' button to fetch about info.
2025-01-25 16:20:26,689 INFO  Fetching channel links.
2025-01-25 16:20:26,786 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 16:20:26,843 INFO  Fetching channel links.
2025-01-25 16:20:26,855 INFO  Closing channel details popup.
2025-01-25 16:20:26,924 INFO  Fetching channel details (subscribers, videos, views, joined date).
2025-01-25 16:20:27,016 INFO  Closing channel details popup.
2025-01-25 16:20:28,160 INFO  Fetching video information for channel: @PewDiePie
2025-01-25 16:20:28,832 INFO  Scrolling through the page to load all videos.
2025-01-25 16:20:44,243 INFO  Extracting video details.
2025-01-25 16:20:44,291 INFO  Fetching additional details for video: OZI0oOfRFp4
2025-01-25 16:20:46,639 INFO  Clicking expand button to reveal more video details.
2025-01-25 16:20:46,830 INFO  Fetching likes count.
2025-01-25 16:20:47,001 INFO  Fetching uploaded date.
2025-01-25 16:21:12,385 INFO  Fetching comments count and details.
2025-01-25 16:21:12,543 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:12,689 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:12,773 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:12,824 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:12,874 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:13,200 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:13,237 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:13,274 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:13,311 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:13,355 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 16:21:13,355 INFO  Fetching video duration.
2025-01-25 16:21:13,370 WARNING  Failed to fetch duration from video OZI0oOfRFp4: invalid literal for int() with base 10: ''
2025-01-25 16:21:13,541 ERROR  Failed to fetch additional video details for OZI0oOfRFp4: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,541 INFO  Saving video info to temp_data/@PewDiePie/videos/OZI0oOfRFp4.json
2025-01-25 16:21:13,541 ERROR  Failed to save video information for OZI0oOfRFp4: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,541 INFO  Extracting video details.
2025-01-25 16:21:13,576 INFO  Fetching additional details for video: yfQAnBol6Jw
2025-01-25 16:21:13,577 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482deb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,578 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e090>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,578 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e270>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,579 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e450>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,579 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e600>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,580 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e7b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,580 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e930>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,581 ERROR  Failed to fetch additional video details for yfQAnBol6Jw: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,581 INFO  Saving video info to temp_data/@PewDiePie/videos/yfQAnBol6Jw.json
2025-01-25 16:21:13,581 ERROR  Failed to save video information for yfQAnBol6Jw: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,581 INFO  Extracting video details.
2025-01-25 16:21:13,607 INFO  Fetching additional details for video: Jzk5gbWQaT8
2025-01-25 16:21:13,608 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482eed0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,609 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482f080>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,609 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482dc40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,610 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482fd70>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,610 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,611 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c230>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,611 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c3e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,612 ERROR  Failed to fetch additional video details for Jzk5gbWQaT8: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,612 INFO  Saving video info to temp_data/@PewDiePie/videos/Jzk5gbWQaT8.json
2025-01-25 16:21:13,612 ERROR  Failed to save video information for Jzk5gbWQaT8: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,612 INFO  Extracting video details.
2025-01-25 16:21:13,639 INFO  Fetching additional details for video: 8fLZQYiI3mg
2025-01-25 16:21:13,640 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482ec00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,640 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482ee40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,641 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e870>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,641 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e930>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,642 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e780>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,642 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482df70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,643 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e3f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,644 ERROR  Failed to fetch additional video details for 8fLZQYiI3mg: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,644 INFO  Saving video info to temp_data/@PewDiePie/videos/8fLZQYiI3mg.json
2025-01-25 16:21:13,644 ERROR  Failed to save video information for 8fLZQYiI3mg: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,644 INFO  Extracting video details.
2025-01-25 16:21:13,671 INFO  Fetching additional details for video: vCqZQOqUiqo
2025-01-25 16:21:13,672 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482fda0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,672 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1048a1d90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,673 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c590>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,673 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c770>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,674 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c980>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,674 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494cb60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,675 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494cd10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,676 ERROR  Failed to fetch additional video details for vCqZQOqUiqo: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,676 INFO  Saving video info to temp_data/@PewDiePie/videos/vCqZQOqUiqo.json
2025-01-25 16:21:13,676 ERROR  Failed to save video information for vCqZQOqUiqo: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,676 INFO  Extracting video details.
2025-01-25 16:21:13,704 INFO  Fetching additional details for video: IkU3c1kERcw
2025-01-25 16:21:13,705 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482d700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,705 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e4e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,706 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e480>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,706 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e780>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,707 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482ec60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,707 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e930>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,708 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482eae0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,709 ERROR  Failed to fetch additional video details for IkU3c1kERcw: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,709 INFO  Saving video info to temp_data/@PewDiePie/videos/IkU3c1kERcw.json
2025-01-25 16:21:13,709 ERROR  Failed to save video information for IkU3c1kERcw: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,709 INFO  Extracting video details.
2025-01-25 16:21:13,736 INFO  Fetching additional details for video: GPLImB-I71w
2025-01-25 16:21:13,736 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482ee10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,737 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c650>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,738 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c5c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,738 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494cf50>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,739 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494d130>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,739 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494d310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,740 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494d4c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,741 ERROR  Failed to fetch additional video details for GPLImB-I71w: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,741 INFO  Saving video info to temp_data/@PewDiePie/videos/GPLImB-I71w.json
2025-01-25 16:21:13,741 ERROR  Failed to save video information for GPLImB-I71w: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,741 INFO  Extracting video details.
2025-01-25 16:21:13,768 INFO  Fetching additional details for video: Jal7jd_ocL0
2025-01-25 16:21:13,768 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482f980>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,769 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e6f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,769 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482df70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,770 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482da90>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,770 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e4e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,771 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e1e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,771 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482f1d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,772 ERROR  Failed to fetch additional video details for Jal7jd_ocL0: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,772 INFO  Saving video info to temp_data/@PewDiePie/videos/Jal7jd_ocL0.json
2025-01-25 16:21:13,772 ERROR  Failed to save video information for Jal7jd_ocL0: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,772 INFO  Extracting video details.
2025-01-25 16:21:13,802 INFO  Fetching additional details for video: Tbwbq-03aOc
2025-01-25 16:21:13,803 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494d100>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,804 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494cec0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,804 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494c7a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,805 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494d730>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,805 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494d910>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,806 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494daf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,806 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10494dca0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,807 ERROR  Failed to fetch additional video details for Tbwbq-03aOc: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,807 INFO  Saving video info to temp_data/@PewDiePie/videos/Tbwbq-03aOc.json
2025-01-25 16:21:13,807 ERROR  Failed to save video information for Tbwbq-03aOc: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 16:21:13,807 INFO  Extracting video details.
2025-01-25 16:21:13,837 INFO  Fetching additional details for video: bzubMYUiCac
2025-01-25 16:21:13,838 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482db50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,839 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482ea50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,839 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e6c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url
2025-01-25 16:21:13,840 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=59949): Max retries exceeded with url: /session/edf98dc27799e3c7f2f5ce9b2522c0f7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e600>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 16:21:13,840 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e6f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,840 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482e900>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,841 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10482f050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/edf98dc27799e3c7f2f5ce9b2522c0f7
2025-01-25 16:21:13,841 ERROR  Failed to fetch additional video details for bzubMYUiCac: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 16:21:13,841 INFO  Saving video info to temp_data/@PewDiePie/videos/bzubMYUiCac.json
2025-01-25 16:21:13,842 ERROR  Failed to save video information for bzubMYUiCac: cannot access local variable 'video_info' where it is not associated with a value
