2025-01-25 09:59:24,921 INFO  Fetching video information for channel: @MrBeast
2025-01-25 09:59:24,927 INFO  Scrolling through the page to load all videos.
2025-01-25 09:59:40,119 INFO  Extracting video details.
2025-01-25 09:59:40,171 INFO  Fetching additional details for video: SM66GDRyIVY
2025-01-25 09:59:44,060 INFO  Clicking expand button to reveal more video details.
2025-01-25 09:59:44,506 INFO  Fetching likes count.
2025-01-25 09:59:44,549 INFO  Fetching uploaded date.
2025-01-25 10:00:10,552 INFO  Fetching comments count and details.
2025-01-25 10:00:10,848 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:00:10,899 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:00:10,953 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:00:11,169 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:00:11,217 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:00:11,259 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:00:11,362 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:00:11,407 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:00:11,408 INFO  Fetching video duration.
2025-01-25 10:00:11,423 WARNING  Failed to fetch duration from video SM66GDRyIVY: invalid literal for int() with base 10: ''
2025-01-25 10:00:11,577 ERROR  Failed to fetch additional video details for SM66GDRyIVY: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,577 INFO  Saving video info to temp_data/@MrBeast/videos/SM66GDRyIVY.json
2025-01-25 10:00:11,577 ERROR  Failed to save video information for SM66GDRyIVY: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,577 INFO  Extracting video details.
2025-01-25 10:00:11,617 INFO  Fetching additional details for video: gs8qfL9PNac
2025-01-25 10:00:11,618 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,618 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c3b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,618 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c590>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,619 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c770>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,619 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c980>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,620 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cb60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,620 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104568ef0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,621 ERROR  Failed to fetch additional video details for gs8qfL9PNac: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,621 INFO  Saving video info to temp_data/@MrBeast/videos/gs8qfL9PNac.json
2025-01-25 10:00:11,621 ERROR  Failed to save video information for gs8qfL9PNac: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,621 INFO  Extracting video details.
2025-01-25 10:00:11,653 INFO  Fetching additional details for video: 0BjlBnfHcHM
2025-01-25 10:00:11,654 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c440>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,654 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cce0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,655 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cec0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,655 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452d0d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,656 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452d310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,656 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452d4f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,657 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452e420>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,657 ERROR  Failed to fetch additional video details for 0BjlBnfHcHM: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,658 INFO  Saving video info to temp_data/@MrBeast/videos/0BjlBnfHcHM.json
2025-01-25 10:00:11,658 ERROR  Failed to save video information for 0BjlBnfHcHM: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,658 INFO  Extracting video details.
2025-01-25 10:00:11,686 INFO  Fetching additional details for video: Xj0Jtjg3lHQ
2025-01-25 10:00:11,687 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452e660>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,688 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452ea80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,688 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452ecc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,689 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452ef00>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,689 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104569700>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,689 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c1d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,690 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452e150>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,691 ERROR  Failed to fetch additional video details for Xj0Jtjg3lHQ: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,691 INFO  Saving video info to temp_data/@MrBeast/videos/Xj0Jtjg3lHQ.json
2025-01-25 10:00:11,691 ERROR  Failed to save video information for Xj0Jtjg3lHQ: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,691 INFO  Extracting video details.
2025-01-25 10:00:11,718 INFO  Fetching additional details for video: bn0Kh9c4Zv4
2025-01-25 10:00:11,719 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c800>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,720 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cef0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,720 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cd40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,721 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c620>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,722 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c0e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,722 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cbc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,722 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452f170>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,723 ERROR  Failed to fetch additional video details for bn0Kh9c4Zv4: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,723 INFO  Saving video info to temp_data/@MrBeast/videos/bn0Kh9c4Zv4.json
2025-01-25 10:00:11,723 ERROR  Failed to save video information for bn0Kh9c4Zv4: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,723 INFO  Extracting video details.
2025-01-25 10:00:11,756 INFO  Fetching additional details for video: snX5YyflrGw
2025-01-25 10:00:11,757 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452f6b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,758 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452fa70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,758 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452fcb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,758 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452fef0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,759 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c6b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,759 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c650>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,760 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452f350>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,760 ERROR  Failed to fetch additional video details for snX5YyflrGw: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,760 INFO  Saving video info to temp_data/@MrBeast/videos/snX5YyflrGw.json
2025-01-25 10:00:11,760 ERROR  Failed to save video information for snX5YyflrGw: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,760 INFO  Extracting video details.
2025-01-25 10:00:11,791 INFO  Fetching additional details for video: aRcUVhVlSHg
2025-01-25 10:00:11,792 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cfe0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,792 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cd70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,793 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c740>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,793 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452d580>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,794 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452e210>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,794 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452dd30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,794 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c1d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,795 ERROR  Failed to fetch additional video details for aRcUVhVlSHg: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,795 INFO  Saving video info to temp_data/@MrBeast/videos/aRcUVhVlSHg.json
2025-01-25 10:00:11,795 ERROR  Failed to save video information for aRcUVhVlSHg: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,795 INFO  Extracting video details.
2025-01-25 10:00:11,825 INFO  Fetching additional details for video: ndAQfTzlVjc
2025-01-25 10:00:11,826 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044f83e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,827 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044f87d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,827 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044f8a10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,827 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452d280>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,828 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452ffe0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,828 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452dfa0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,829 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452e1e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,830 ERROR  Failed to fetch additional video details for ndAQfTzlVjc: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,830 INFO  Saving video info to temp_data/@MrBeast/videos/ndAQfTzlVjc.json
2025-01-25 10:00:11,830 ERROR  Failed to save video information for ndAQfTzlVjc: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,830 INFO  Extracting video details.
2025-01-25 10:00:11,858 INFO  Fetching additional details for video: UPrkC1LdlLY
2025-01-25 10:00:11,859 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452ce60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,859 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c680>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,860 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452cb60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,860 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452f380>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,860 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452c6b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,861 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452fef0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,861 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044f8620>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,862 ERROR  Failed to fetch additional video details for UPrkC1LdlLY: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,862 INFO  Saving video info to temp_data/@MrBeast/videos/UPrkC1LdlLY.json
2025-01-25 10:00:11,862 ERROR  Failed to save video information for UPrkC1LdlLY: 'dict' object has no attribute 'model_dump_json'
2025-01-25 10:00:11,862 INFO  Extracting video details.
2025-01-25 10:00:11,890 INFO  Fetching additional details for video: 4SNThp0YiU4
2025-01-25 10:00:11,891 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044f8f20>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,891 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044f9310>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,892 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1044f9550>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82/url
2025-01-25 10:00:11,893 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=64924): Max retries exceeded with url: /session/3d44580e3c6820072f5352360200ae82/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10456b4d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:00:11,894 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452eff0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,894 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452fec0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,894 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10452f530>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/3d44580e3c6820072f5352360200ae82
2025-01-25 10:00:11,895 ERROR  Failed to fetch additional video details for 4SNThp0YiU4: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:00:11,895 INFO  Saving video info to temp_data/@MrBeast/videos/4SNThp0YiU4.json
2025-01-25 10:00:11,895 ERROR  Failed to save video information for 4SNThp0YiU4: 'dict' object has no attribute 'model_dump_json'
