2025-01-25 15:50:19,973 INFO  Fetching video information for channel: @MrBeast
2025-01-25 15:50:19,988 INFO  Scrolling through the page to load all videos.
2025-01-25 15:50:35,248 INFO  Extracting video details.
2025-01-25 15:50:35,296 INFO  Fetching additional details for video: SM66GDRyIVY
2025-01-25 15:50:35,296 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=SM66GDRyIVY
2025-01-25 15:50:39,100 INFO  Clicking expand button to reveal more video details.
2025-01-25 15:50:39,399 INFO  Fetching likes count.
2025-01-25 15:50:47,755 ERROR  Failed to fetch likes count.
2025-01-25 15:50:47,756 INFO  Fetching uploaded date.
2025-01-25 15:51:12,652 INFO  Fetching comments count and details.
2025-01-25 15:51:12,794 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 15:51:12,962 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 15:51:13,000 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 15:51:13,036 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 15:51:13,075 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 15:51:13,154 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 15:51:13,192 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 15:51:13,231 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 15:51:13,231 INFO  Fetching video duration.
2025-01-25 15:51:13,239 WARNING  Failed to fetch duration from video SM66GDRyIVY: invalid literal for int() with base 10: ''
2025-01-25 15:51:13,369 ERROR  Failed to fetch additional video details for SM66GDRyIVY: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,369 INFO  Extracting video details.
2025-01-25 15:51:13,399 INFO  Fetching additional details for video: gs8qfL9PNac
2025-01-25 15:51:13,399 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=gs8qfL9PNac
2025-01-25 15:51:13,400 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d370>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,401 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d910>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,401 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711db50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,402 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711dd30>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,402 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711dfd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,403 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711e1e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,403 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711e390>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,404 ERROR  Failed to fetch additional video details for gs8qfL9PNac: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,404 INFO  Extracting video details.
2025-01-25 15:51:13,430 INFO  Fetching additional details for video: 0BjlBnfHcHM
2025-01-25 15:51:13,430 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=0BjlBnfHcHM
2025-01-25 15:51:13,431 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f500>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,431 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f680>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,432 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f8c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,432 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711fb00>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,433 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711fe00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,433 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,434 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384200>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,435 ERROR  Failed to fetch additional video details for 0BjlBnfHcHM: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,435 INFO  Extracting video details.
2025-01-25 15:51:13,462 INFO  Fetching additional details for video: Xj0Jtjg3lHQ
2025-01-25 15:51:13,462 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=Xj0Jtjg3lHQ
2025-01-25 15:51:13,465 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,465 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10714ef30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,466 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711fe60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,466 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f5c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,467 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711fa70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,467 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f6b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,468 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f500>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,469 ERROR  Failed to fetch additional video details for Xj0Jtjg3lHQ: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,469 INFO  Extracting video details.
2025-01-25 15:51:13,495 INFO  Fetching additional details for video: bn0Kh9c4Zv4
2025-01-25 15:51:13,495 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=bn0Kh9c4Zv4
2025-01-25 15:51:13,496 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711e4e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,496 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d4f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,497 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d0a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,497 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711da30>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,498 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d100>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,498 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711ddc0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,499 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d280>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,500 ERROR  Failed to fetch additional video details for bn0Kh9c4Zv4: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,500 INFO  Extracting video details.
2025-01-25 15:51:13,526 INFO  Fetching additional details for video: snX5YyflrGw
2025-01-25 15:51:13,526 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=snX5YyflrGw
2025-01-25 15:51:13,527 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711fcb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,528 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711e4e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,528 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711da60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,529 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d7f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,529 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f680>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,530 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f8c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,530 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384a40>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,531 ERROR  Failed to fetch additional video details for snX5YyflrGw: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,531 INFO  Extracting video details.
2025-01-25 15:51:13,557 INFO  Fetching additional details for video: aRcUVhVlSHg
2025-01-25 15:51:13,557 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=aRcUVhVlSHg
2025-01-25 15:51:13,558 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384aa0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,559 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384e90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,559 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1073850d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,560 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385310>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,560 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f6e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,561 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d910>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,561 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711daf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,562 ERROR  Failed to fetch additional video details for aRcUVhVlSHg: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,562 INFO  Extracting video details.
2025-01-25 15:51:13,589 INFO  Fetching additional details for video: ndAQfTzlVjc
2025-01-25 15:51:13,589 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=ndAQfTzlVjc
2025-01-25 15:51:13,589 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d880>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,590 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711e1b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,590 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384950>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,591 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1073849e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,591 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385580>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,592 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385760>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,592 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385910>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,593 ERROR  Failed to fetch additional video details for ndAQfTzlVjc: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,593 INFO  Extracting video details.
2025-01-25 15:51:13,620 INFO  Fetching additional details for video: UPrkC1LdlLY
2025-01-25 15:51:13,620 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=UPrkC1LdlLY
2025-01-25 15:51:13,621 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385fa0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,621 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711e2d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,622 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711e180>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,622 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d010>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,623 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711eba0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,623 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711f650>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,624 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10711d850>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,625 ERROR  Failed to fetch additional video details for UPrkC1LdlLY: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 15:51:13,625 INFO  Extracting video details.
2025-01-25 15:51:13,651 INFO  Fetching additional details for video: 4SNThp0YiU4
2025-01-25 15:51:13,651 INFO  Attempting to fetch video page: https://www.youtube.com/watch?v=4SNThp0YiU4
2025-01-25 15:51:13,651 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107385880>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,652 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384410>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,652 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384380>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59/url
2025-01-25 15:51:13,653 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=52451): Max retries exceeded with url: /session/2d9c1c86a86a225620ebaf5d32fb1e59/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107384a10>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 15:51:13,653 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107386360>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,654 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107386570>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,654 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x107386720>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/2d9c1c86a86a225620ebaf5d32fb1e59
2025-01-25 15:51:13,655 ERROR  Failed to fetch additional video details for 4SNThp0YiU4: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
