2025-01-25 10:00:40,171 INFO  Fetching video information for channel: @MrBeast
2025-01-25 10:00:40,178 INFO  Scrolling through the page to load all videos.
2025-01-25 10:00:55,391 INFO  Extracting video details.
2025-01-25 10:00:55,445 INFO  Fetching additional details for video: SM66GDRyIVY
2025-01-25 10:00:59,051 INFO  Clicking expand button to reveal more video details.
2025-01-25 10:00:59,544 INFO  Fetching likes count.
2025-01-25 10:00:59,599 INFO  Fetching uploaded date.
2025-01-25 10:01:24,652 INFO  Fetching comments count and details.
2025-01-25 10:01:24,813 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:01:24,857 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:01:24,896 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:01:24,972 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:01:25,010 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:01:25,050 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:01:25,125 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:01:25,163 ERROR  Failed to fetch comment details: 1 validation error for Comment
replies_count
  Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/int_type
2025-01-25 10:01:25,163 INFO  Fetching video duration.
2025-01-25 10:01:25,171 WARNING  Failed to fetch duration from video SM66GDRyIVY: invalid literal for int() with base 10: ''
2025-01-25 10:01:25,302 ERROR  Failed to fetch additional video details for SM66GDRyIVY: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,302 INFO  Saving video info to temp_data/@MrBeast/videos/SM66GDRyIVY.json
2025-01-25 10:01:25,302 ERROR  Failed to save video information for SM66GDRyIVY: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,302 INFO  Extracting video details.
2025-01-25 10:01:25,333 INFO  Fetching additional details for video: gs8qfL9PNac
2025-01-25 10:01:25,334 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10050>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,334 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10560>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,335 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10740>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,335 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10920>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,336 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10b30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,336 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10d10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,336 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f4f1a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,337 ERROR  Failed to fetch additional video details for gs8qfL9PNac: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,337 INFO  Saving video info to temp_data/@MrBeast/videos/gs8qfL9PNac.json
2025-01-25 10:01:25,337 ERROR  Failed to save video information for gs8qfL9PNac: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,337 INFO  Extracting video details.
2025-01-25 10:01:25,362 INFO  Fetching additional details for video: 0BjlBnfHcHM
2025-01-25 10:01:25,363 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f102c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,363 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10e30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,364 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11040>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,364 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11250>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,365 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11490>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,365 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11670>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,365 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11820>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,366 ERROR  Failed to fetch additional video details for 0BjlBnfHcHM: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,366 INFO  Saving video info to temp_data/@MrBeast/videos/0BjlBnfHcHM.json
2025-01-25 10:01:25,366 ERROR  Failed to save video information for 0BjlBnfHcHM: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,366 INFO  Extracting video details.
2025-01-25 10:01:25,394 INFO  Fetching additional details for video: Xj0Jtjg3lHQ
2025-01-25 10:01:25,395 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f12660>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,396 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f12b70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,396 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f12db0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,396 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f12ff0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,397 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f122d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,397 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f115b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,397 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11a60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,398 ERROR  Failed to fetch additional video details for Xj0Jtjg3lHQ: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,398 INFO  Saving video info to temp_data/@MrBeast/videos/Xj0Jtjg3lHQ.json
2025-01-25 10:01:25,398 ERROR  Failed to save video information for Xj0Jtjg3lHQ: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,398 INFO  Extracting video details.
2025-01-25 10:01:25,425 INFO  Fetching additional details for video: bn0Kh9c4Zv4
2025-01-25 10:01:25,426 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f101a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,426 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11010>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,426 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f105f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,427 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10680>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,427 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f106e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,427 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10d70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,428 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f13260>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,428 ERROR  Failed to fetch additional video details for bn0Kh9c4Zv4: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,429 INFO  Saving video info to temp_data/@MrBeast/videos/bn0Kh9c4Zv4.json
2025-01-25 10:01:25,429 ERROR  Failed to save video information for bn0Kh9c4Zv4: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,429 INFO  Extracting video details.
2025-01-25 10:01:25,454 INFO  Fetching additional details for video: snX5YyflrGw
2025-01-25 10:01:25,454 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f137a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,455 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f13b60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,455 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f13da0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,456 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f13fe0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,456 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10ce0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,456 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f13470>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,457 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f13230>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,457 ERROR  Failed to fetch additional video details for snX5YyflrGw: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,457 INFO  Saving video info to temp_data/@MrBeast/videos/snX5YyflrGw.json
2025-01-25 10:01:25,457 ERROR  Failed to save video information for snX5YyflrGw: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,457 INFO  Extracting video details.
2025-01-25 10:01:25,482 INFO  Fetching additional details for video: aRcUVhVlSHg
2025-01-25 10:01:25,483 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f13620>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,484 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f110a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,484 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11100>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,484 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f114c0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,485 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f116a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,485 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,485 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f11400>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,486 ERROR  Failed to fetch additional video details for aRcUVhVlSHg: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,486 INFO  Saving video info to temp_data/@MrBeast/videos/aRcUVhVlSHg.json
2025-01-25 10:01:25,486 ERROR  Failed to save video information for aRcUVhVlSHg: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,486 INFO  Extracting video details.
2025-01-25 10:01:25,511 INFO  Fetching additional details for video: ndAQfTzlVjc
2025-01-25 10:01:25,512 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ee44d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,512 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ee48c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,512 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ee4b00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,513 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10530>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,513 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f107d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,514 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f116a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,514 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f100b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,515 ERROR  Failed to fetch additional video details for ndAQfTzlVjc: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,515 INFO  Saving video info to temp_data/@MrBeast/videos/ndAQfTzlVjc.json
2025-01-25 10:01:25,515 ERROR  Failed to save video information for ndAQfTzlVjc: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,515 INFO  Extracting video details.
2025-01-25 10:01:25,540 INFO  Fetching additional details for video: UPrkC1LdlLY
2025-01-25 10:01:25,540 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f112e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,541 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f103b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,541 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10410>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,542 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f13470>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,542 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10cb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,542 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ee43e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,543 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ee41d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,543 ERROR  Failed to fetch additional video details for UPrkC1LdlLY: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,543 INFO  Saving video info to temp_data/@MrBeast/videos/UPrkC1LdlLY.json
2025-01-25 10:01:25,543 ERROR  Failed to save video information for UPrkC1LdlLY: cannot access local variable 'video_info' where it is not associated with a value
2025-01-25 10:01:25,543 INFO  Extracting video details.
2025-01-25 10:01:25,569 INFO  Fetching additional details for video: 4SNThp0YiU4
2025-01-25 10:01:25,570 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ee4fe0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,571 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ee53d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,572 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106ee5610>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7/url
2025-01-25 10:01:25,572 ERROR  Unexpected error occurred: HTTPConnectionPool(host='localhost', port=65493): Max retries exceeded with url: /session/d0e0412cb9b6876734c8c6e89b50e0a7/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f4df70>: Failed to establish a new connection: [Errno 61] Connection refused'))
2025-01-25 10:01:25,573 WARNING  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10cb0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,573 WARNING  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,573 WARNING  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106f10d70>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/d0e0412cb9b6876734c8c6e89b50e0a7
2025-01-25 10:01:25,574 ERROR  Failed to fetch additional video details for 4SNThp0YiU4: 1 validation error for VideoInfo
duration
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/float_parsing
2025-01-25 10:01:25,574 INFO  Saving video info to temp_data/@MrBeast/videos/4SNThp0YiU4.json
2025-01-25 10:01:25,574 ERROR  Failed to save video information for 4SNThp0YiU4: cannot access local variable 'video_info' where it is not associated with a value
